import { Marcellus } from 'next/font/google'
import './globals.css'
import { GoogleAnalytics } from '@next/third-parties/google'

const marcellus = Marcellus({ weight: '400', subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={marcellus.className}>{children}</body>
      <GoogleAnalytics gaId="G-4SSR96YT03" />
    </html>
  )
}
